name: Publish to PyPI

on:
  release:
    types:
      published

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image to production
        run: |
          pip install uv
          uv run build
