name: Publish to PyPI

on:
  release:
    types:
      published

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to PyPI
        run: |
          pip install uv
          uv build
          uv publish
